import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { Search, SlidersHorizontal, Heart, ArrowUpRight, Sparkles, Plus, X, MessageCircle, BarChart3, LogIn, Send, Home, ChevronDown, MapPin } from "lucide-react";
import "@/App.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const fallback = [
  { id: "p1", title: "The Glasshouse", city: "Austin, TX", neighborhood: "Westlake", price: 2450000, beds: 4, baths: 3.5, sqft: 3860, type: "Villa", image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=85", tags: ["Pool", "Smart home", "Lake view"], aiScore: 98 },
  { id: "p2", title: "No. 28 Penthouse", city: "Miami, FL", neighborhood: "Brickell", price: 1780000, beds: 3, baths: 2.5, sqft: 2190, type: "Penthouse", image: "https://images.unsplash.com/photo-1776362355123-ca966d36e29c?auto=format&fit=crop&w=1200&q=85", tags: ["Skyline", "Concierge", "Terrace"], aiScore: 95 },
  { id: "p3", title: "Canyon House", city: "Los Angeles, CA", neighborhood: "Los Feliz", price: 3295000, beds: 5, baths: 4, sqft: 4210, type: "House", image: "https://images.pexels.com/photos/6970051/pexels-photo-6970051.jpeg?auto=compress&cs=tinysrgb&w=1200", tags: ["Garden", "Views", "Guest suite"], aiScore: 91 },
];
const money = (n) => `$${(n / 1000000).toFixed(n >= 1000000 ? 2 : 1)}M`;

function PropertyCard({ property, saved, compared, onSave, onCompare, onOpen }) {
  return <article className="property-card" data-testid={`property-card-${property.id}`}>
    <div className="property-image-wrap"><img src={property.image} alt={property.title} className="property-image" /><span className="score">{property.aiScore}% AI fit</span><button className={`icon-button ${saved ? "is-saved" : ""}`} data-testid={`wishlist-${property.id}`} onClick={() => onSave(property.id)} aria-label="Save property"><Heart size={17} fill={saved ? "currentColor" : "none"} /></button></div>
    <div className="property-content"><div className="eyebrow-row"><span>{property.type}</span><span>{property.neighborhood}</span></div><h3 data-testid={`property-title-${property.id}`}>{property.title}</h3><p className="property-location"><MapPin size={14} /> {property.city}</p><div className="property-specs"><span>{property.beds} beds</span><span>{property.baths} baths</span><span>{property.sqft.toLocaleString()} sqft</span></div><div className="property-bottom"><strong>{money(property.price)}</strong><button className={compared ? "compare active" : "compare"} data-testid={`compare-${property.id}`} onClick={() => onCompare(property.id)}><BarChart3 size={14} /> {compared ? "Added" : "Compare"}</button><button className="arrow-button" data-testid={`open-property-${property.id}`} onClick={() => onOpen(property)}><ArrowUpRight size={17} /></button></div></div>
  </article>;
}

function AuthModal({ mode, setMode, onClose, onSuccess }) {
  const [form, setForm] = useState({ name: "", email: "buyer@lumina.demo", password: "Lumina2026!", role: "buyer" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (e) => { e.preventDefault(); setLoading(true); setError(""); try { const r = await axios.post(`${API}/auth/${mode}`, form); localStorage.setItem("lumina_token", r.data.token); onSuccess(r.data.user); onClose(); } catch (err) { setError(err.response?.data?.message || "Unable to continue right now."); } finally { setLoading(false); } };
  return <div className="modal-backdrop" data-testid="auth-modal"><div className="auth-modal"><button className="close-button" data-testid="close-auth-button" onClick={onClose}><X /></button><span className="auth-mark"><Sparkles size={18} /></span><p className="kicker">LUMINA ESTATES</p><h2>{mode === "login" ? "Welcome back." : "Make room for more."}</h2><p className="muted">{mode === "login" ? "Your next address is waiting." : "Join a more considered way to find home."}</p><form onSubmit={submit}>{mode === "register" && <input data-testid="auth-name-input" placeholder="Full name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required />}<input data-testid="auth-email-input" type="email" placeholder="Email address" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} required /><input data-testid="auth-password-input" type="password" placeholder="Password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} required />{mode === "register" && <select data-testid="auth-role-select" value={form.role} onChange={e => setForm({ ...form, role: e.target.value })}><option value="buyer">I’m looking for a home</option><option value="seller">I’m listing a property</option></select>}{error && <p className="error" data-testid="auth-error">{error}</p>}<button className="gold-button full" data-testid="auth-submit-button" disabled={loading}>{loading ? "Opening your account…" : mode === "login" ? "Enter Lumina" : "Create account"}</button></form><button className="text-button" data-testid="auth-mode-toggle" onClick={() => setMode(mode === "login" ? "register" : "login")}>{mode === "login" ? "New here? Create an account" : "Already have an account? Sign in"}</button><p className="demo-note">Demo access: buyer@lumina.demo · Lumina2026!</p></div></div>;
}

function App() {
  const [properties, setProperties] = useState(fallback); const [query, setQuery] = useState(""); const [type, setType] = useState("All"); const [saved, setSaved] = useState([]); const [compare, setCompare] = useState([]); const [user, setUser] = useState(null); const [auth, setAuth] = useState(null); const [assistantOpen, setAssistantOpen] = useState(false); const [assistantText, setAssistantText] = useState(""); const [answer, setAnswer] = useState(null); const [selected, setSelected] = useState(null); const [menuOpen, setMenuOpen] = useState(false); const [loading, setLoading] = useState(true);
  const token = localStorage.getItem("lumina_token"); const headers = token ? { Authorization: `Bearer ${token}` } : {};
  useEffect(() => { Promise.all([axios.get(`${API}/properties`), token ? axios.get(`${API}/auth/me`, { headers }) : Promise.resolve(null)]).then(([p, me]) => { if (p.data.properties?.length) setProperties(p.data.properties); if (me?.data.user) setUser(me.data.user); }).catch(() => {}).finally(() => setLoading(false)); }, []); // eslint-disable-line
  useEffect(() => { if (token) axios.get(`${API}/me/saved`, { headers }).then(r => { setSaved(r.data.wishlist.map(x => x.id)); setCompare(r.data.compare || []); }).catch(() => {}); }, [user]); // eslint-disable-line
  const filtered = useMemo(() => properties.filter(p => (!query || `${p.title} ${p.city} ${p.neighborhood} ${p.tags?.join(" ")}`.toLowerCase().includes(query.toLowerCase())) && (type === "All" || p.type === type)), [properties, query, type]);
  const save = async (id) => { if (!token) return setAuth("login"); const r = await axios.post(`${API}/me/wishlist/${id}`, {}, { headers }); setSaved(r.data.wishlist); };
  const toggleCompare = async (id) => { if (!token) return setAuth("login"); const r = await axios.post(`${API}/me/compare/${id}`, {}, { headers }); setCompare(r.data.compare); };
  const ask = async (e) => { e?.preventDefault(); if (!assistantText.trim()) return; setAnswer({ loading: true }); try { const r = await axios.post(`${API}/ai/assistant`, { prompt: assistantText }); setAnswer(r.data); } catch { setAnswer({ reply: "I’m having trouble reaching the property intelligence layer. Try again in a moment." }); } };
  const logout = () => { localStorage.removeItem("lumina_token"); setUser(null); setMenuOpen(false); };
  return <div className="app-shell"><header className="topbar"><a className="brand" href="#top" data-testid="brand-link"><span className="brand-icon"><Sparkles size={15} /></span><span>LUMINA <b>ESTATES</b></span></a><nav className="main-nav"><a href="#discover" data-testid="nav-discover">Discover</a><a href="#approach" data-testid="nav-approach">Our approach</a><a href="#insights" data-testid="nav-insights">Insights</a></nav><div className="header-actions">{user ? <div className="user-menu"><button className="user-pill" data-testid="user-menu-button" onClick={() => setMenuOpen(!menuOpen)}><span>{user.initials}</span>{user.name.split(" ")[0]}<ChevronDown size={14} /></button>{menuOpen && <div className="dropdown"><button data-testid="dashboard-link" onClick={() => document.getElementById("dashboard").scrollIntoView({ behavior: "smooth" })}>My dashboard</button><button data-testid="logout-button" onClick={logout}>Sign out</button></div>}</div> : <button className="login-button" data-testid="header-login-button" onClick={() => setAuth("login")}><LogIn size={16} /> Sign in</button>}<button className="plus-button" data-testid="list-property-button" onClick={() => user?.role === "seller" ? setSelected({ create: true }) : setAuth("login")}><Plus size={17} /> List a property</button></div></header>
    <main id="top"><section className="hero"><div className="hero-copy"><p className="kicker reveal">CURATED REAL ESTATE · INTELLIGENTLY MATCHED</p><h1 className="reveal delay-1">Find a place<br /><em>worth living in.</em></h1><p className="hero-sub reveal delay-2">A considered collection of exceptional homes, guided by intelligence that understands what makes a place feel like yours.</p><div className="search-panel reveal delay-3"><div className="search-icon"><Search size={20} /></div><input data-testid="property-search-input" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by city, neighborhood, or home type" /><button className="gold-button" data-testid="search-button" onClick={() => document.getElementById("discover").scrollIntoView({ behavior: "smooth" })}>Explore homes <ArrowUpRight size={16} /></button></div><div className="hero-meta reveal delay-3"><span><i></i> 1,240+ homes carefully selected</span><span>Live in 18 cities</span></div></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1776362355123-ca966d36e29c?crop=entropy&cs=srgb&fm=jpg&q=85" alt="Modern penthouse interior" /><div className="visual-caption"><span>01 / 06</span><strong>No. 28 Penthouse</strong><small>Brickell · Miami, FL</small></div></div></section>
      <section className="trust-strip" data-testid="trust-strip"><span>TRUSTED BY PEOPLE WHO VALUE HOME</span><b>ARCHITECTURAL DIGEST</b><b>Monocle</b><b>FORBES</b><b>THE WALL STREET JOURNAL</b></section>
      <section className="section discover-section" id="discover"><div className="section-heading"><div><p className="kicker">THE COLLECTION</p><h2>Homes with <em>character.</em></h2></div><p className="section-intro">Not more listings. Better ones. Every property is reviewed for its architecture, setting, and the life it makes possible.</p></div><div className="filter-row"><div className="type-tabs">{["All", "Villa", "Penthouse", "House", "Loft"].map(t => <button key={t} className={type === t ? "active" : ""} data-testid={`filter-${t.toLowerCase()}`} onClick={() => setType(t)}>{t}</button>)}</div><button className="filter-button" data-testid="advanced-filters-button"><SlidersHorizontal size={16} /> Filters</button></div>{loading ? <div className="loading-state" data-testid="properties-loading">Curating the collection…</div> : <div className="property-grid">{filtered.map(p => <PropertyCard key={p.id} property={p} saved={saved.includes(p.id)} compared={compare.includes(p.id)} onSave={save} onCompare={toggleCompare} onOpen={setSelected} />)}</div>}{!filtered.length && <div className="empty-state" data-testid="empty-properties">No homes match that search. Try another city or type.</div>}</section>
      <section className="ai-band" id="approach"><div className="ai-copy"><span className="ai-symbol"><Sparkles size={22} /></span><p className="kicker">YOUR PRIVATE PROPERTY INTELLIGENCE</p><h2>Search like you<br /><em>already know.</em></h2><p>Tell Lumina what you’re looking for in your own words. It reads between the lines — budget, feeling, future — and surfaces the homes that make sense.</p><button className="outline-button" data-testid="open-assistant-button" onClick={() => setAssistantOpen(true)}>Ask Lumina <ArrowUpRight size={16} /></button></div><div className="ai-example"><div className="chat-label"><span className="online-dot"></span> LUMINA ASSISTANT <span>AI</span></div><p>“I want somewhere quiet and green, close enough to a good restaurant. Under $2M.”</p><div className="ai-result"><div className="mini-image"><img src={fallback[0].image} alt="The Glasshouse" /></div><div><small>BEST MATCH · 98% FIT</small><strong>The Glasshouse</strong><span>Westlake · Austin, TX</span></div><ArrowUpRight size={18} /></div></div></section>
      <section className="section dashboard-section" id="dashboard"><div className="section-heading"><div><p className="kicker">YOUR LUMINA</p><h2>A clearer <em>next move.</em></h2></div><p className="section-intro">Save possibilities, compare the details, and let the numbers become part of the story.</p></div><div className="dashboard-grid"><div className="metric-panel"><span className="kicker">PORTFOLIO PULSE</span><strong data-testid="dashboard-metric">{user ? "14" : "—"}</strong><p>{user ? "properties matching your profile" : "Sign in to see your matches"}</p><button className="text-link" data-testid="dashboard-action" onClick={() => user ? setAssistantOpen(true) : setAuth("login")}>{user ? "Open your intelligence" : "Sign in to unlock"} <ArrowUpRight size={14} /></button></div><div className="insight-panel" id="insights"><div className="insight-icon"><BarChart3 /></div><p className="kicker">MARKET SIGNAL · Q2 2026</p><h3>Thoughtful homes are holding their value.</h3><p>Properties with a strong sense of place are seeing 12% more qualified interest this quarter.</p><button className="text-link" data-testid="market-insights-button">Read the insight <ArrowUpRight size={14} /></button></div><div className="message-panel"><div className="message-header"><MessageCircle size={19} /><span>DIRECT LINE</span><i></i></div><h3>Have a question<br />about a home?</h3><p>Connect directly with the person who knows it best.</p><button className="dark-button" data-testid="message-seller-button" onClick={() => user ? setSelected({ contact: true }) : setAuth("login")}>Start a conversation <Send size={15} /></button></div></div></section>
    </main>
    <footer><a className="brand" href="#top" data-testid="footer-brand"><span className="brand-icon"><Sparkles size={15} /></span><span>LUMINA <b>ESTATES</b></span></a><span>© 2026 Lumina Estates</span><span>Made for the way you want to live.</span></footer>
    {auth && <AuthModal mode={auth} setMode={setAuth} onClose={() => setAuth(null)} onSuccess={setUser} />}
    {assistantOpen && <div className="modal-backdrop" data-testid="assistant-modal"><div className="assistant-modal"><div className="modal-head"><div><p className="kicker">PRIVATE PROPERTY INTELLIGENCE</p><h2>Ask Lumina.</h2></div><button className="close-button" data-testid="close-assistant-button" onClick={() => setAssistantOpen(false)}><X /></button></div><p className="muted">Describe the feeling, the practicalities, or the investment. I’ll connect the dots.</p><form className="assistant-form" onSubmit={ask}><textarea data-testid="assistant-input" value={assistantText} onChange={e => setAssistantText(e.target.value)} placeholder="A light-filled home near the water, under $2M…" rows="3" /><button className="gold-button" data-testid="assistant-submit-button"><Sparkles size={16} /> Find my matches</button></form>{answer?.loading && <p className="loading-state" data-testid="assistant-loading">Reading the brief…</p>}{answer?.reply && <div className="assistant-answer" data-testid="assistant-answer"><span className="ai-symbol"><Sparkles size={16} /></span><p>{answer.reply}</p>{answer.properties?.map(p => <div className="answer-property" key={p.id}><img src={p.image} alt={p.title} /><div><strong>{p.title}</strong><span>{p.city} · {money(p.price)}</span></div><span className="score">{p.aiScore}%</span></div>)}</div>}</div></div>}
    {selected && <div className="modal-backdrop" data-testid="property-modal"><div className="detail-modal">{selected.create ? <><button className="close-button" data-testid="close-detail-button" onClick={() => setSelected(null)}><X /></button><p className="kicker">SELLER STUDIO</p><h2>List your next<br /><em>great address.</em></h2><p className="muted">Your seller dashboard is ready for the full listing flow. Tell us about the home to begin.</p><input data-testid="listing-title-input" placeholder="Property title" /><button className="gold-button full" data-testid="listing-start-button" onClick={() => setSelected(null)}>Start listing <ArrowUpRight size={16} /></button></> : selected.contact ? <><button className="close-button" data-testid="close-detail-button" onClick={() => setSelected(null)}><X /></button><p className="kicker">DIRECT LINE</p><h2>Start a conversation.</h2><textarea data-testid="message-input" placeholder="Write a thoughtful note…" rows="5" /><button className="gold-button full" data-testid="send-message-button" onClick={() => setSelected(null)}>Send message <Send size={16} /></button></> : <><button className="close-button" data-testid="close-detail-button" onClick={() => setSelected(null)}><X /></button><img className="detail-image" src={selected.image} alt={selected.title} /><p className="kicker">{selected.type} · {selected.neighborhood}</p><h2>{selected.title}</h2><p className="property-location"><MapPin size={14} /> {selected.city}</p><div className="detail-specs"><b>{money(selected.price)}</b><span>{selected.beds} beds</span><span>{selected.baths} baths</span><span>{selected.sqft.toLocaleString()} sqft</span></div><p className="muted">{selected.description}</p><button className="gold-button full" data-testid="detail-contact-button" onClick={() => user ? setSelected({ contact: true }) : setAuth("login")}>Enquire about this home <ArrowUpRight size={16} /></button></>}</div></div>}
  </div>;
}
export default App;